// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.model;

public interface AddressOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes hash = 1;</code>
   *
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();
}
