// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.model;

public final class Ethtx {
  static final com.google.protobuf.Descriptors.Descriptor internal_static_Address_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_TxRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_Response_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor internal_static_Tx_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tx_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\013ethtx.proto\"\027\n\007Address\022\014\n\004hash\030\001 \001(\014\"6"
          + "\n\tTxRequest\022\031\n\007address\030\001 \001(\0132\010.Address\022\016"
          + "\n\006txHash\030\002 \001(\014\"\033\n\010Response\022\017\n\007success\030\001 "
          + "\001(\010\"\222\001\n\002Tx\022\014\n\004hash\030\001 \001(\014\022\021\n\ttimestamp\030\002 "
          + "\001(\004\022\026\n\004from\030\003 \001(\0132\010.Address\022\024\n\002to\030\004 \001(\0132"
          + "\010.Address\022\r\n\005value\030\005 \001(\004\022\013\n\003gas\030\006 \001(\004\022\020\n"
          + "\010gasPrice\030\007 \001(\004\022\017\n\007success\030\010 \001(\0102\253\001\n\005Eth"
          + "Tx\022+\n\022SubscribeToAddress\022\010.Address\032\t.Res"
          + "ponse\"\000\022-\n\024UnsubscribeToAddress\022\010.Addres"
          + "s\032\t.Response\"\000\022\036\n\013GetLatestTx\022\010.Address\032"
          + "\003.Tx\"\000\022&\n\rGetPreviousTx\022\n.TxRequest\032\003.Tx"
          + "\"\000(\0010\001B\035\n\031com.mttbrt.ethtxmon.modelP\001b\006p"
          + "roto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_Address_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Address_descriptor,
            new java.lang.String[] {
              "Hash",
            });
    internal_static_TxRequest_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_TxRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_TxRequest_descriptor,
            new java.lang.String[] {
              "Address", "TxHash",
            });
    internal_static_Response_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Response_descriptor,
            new java.lang.String[] {
              "Success",
            });
    internal_static_Tx_descriptor = getDescriptor().getMessageTypes().get(3);
    internal_static_Tx_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Tx_descriptor,
            new java.lang.String[] {
              "Hash", "Timestamp", "From", "To", "Value", "Gas", "GasPrice", "Success",
            });
  }
  private Ethtx() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
