// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.model;

/** Protobuf type {@code Tx} */
public final class Tx extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:Tx)
    TxOrBuilder {
  public static final int HASH_FIELD_NUMBER = 1;
  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  public static final int FROM_FIELD_NUMBER = 3;
  public static final int TO_FIELD_NUMBER = 4;
  public static final int VALUE_FIELD_NUMBER = 5;
  public static final int GAS_FIELD_NUMBER = 6;
  public static final int GASPRICE_FIELD_NUMBER = 7;
  public static final int SUCCESS_FIELD_NUMBER = 8;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:Tx)
  private static final com.mttbrt.ethtxmon.model.Tx DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<Tx> PARSER =
      new com.google.protobuf.AbstractParser<Tx>() {
        @java.lang.Override
        public Tx parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  static {
    DEFAULT_INSTANCE = new com.mttbrt.ethtxmon.model.Tx();
  }

  private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
  private long timestamp_ = 0L;
  private com.mttbrt.ethtxmon.model.Address from_;
  private com.mttbrt.ethtxmon.model.Address to_;
  private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
  private long gas_ = 0L;
  private long gasPrice_ = 0L;
  private boolean success_ = false;
  private byte memoizedIsInitialized = -1;
  // Use Tx.newBuilder() to construct.
  private Tx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Tx() {
    hash_ = com.google.protobuf.ByteString.EMPTY;
    value_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.mttbrt.ethtxmon.model.Ethtx.internal_static_Tx_descriptor;
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.model.Tx parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.mttbrt.ethtxmon.model.Tx prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.mttbrt.ethtxmon.model.Tx getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<Tx> parser() {
    return PARSER;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new Tx();
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mttbrt.ethtxmon.model.Ethtx.internal_static_Tx_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mttbrt.ethtxmon.model.Tx.class, com.mttbrt.ethtxmon.model.Tx.Builder.class);
  }

  /**
   * <code>bytes hash = 1;</code>
   *
   * @return The hash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHash() {
    return hash_;
  }

  /**
   * <code>uint64 timestamp = 2;</code>
   *
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  /**
   * <code>.Address from = 3;</code>
   *
   * @return Whether the from field is set.
   */
  @java.lang.Override
  public boolean hasFrom() {
    return from_ != null;
  }

  /**
   * <code>.Address from = 3;</code>
   *
   * @return The from.
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.model.Address getFrom() {
    return from_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : from_;
  }

  /** <code>.Address from = 3;</code> */
  @java.lang.Override
  public com.mttbrt.ethtxmon.model.AddressOrBuilder getFromOrBuilder() {
    return from_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : from_;
  }

  /**
   * <code>.Address to = 4;</code>
   *
   * @return Whether the to field is set.
   */
  @java.lang.Override
  public boolean hasTo() {
    return to_ != null;
  }

  /**
   * <code>.Address to = 4;</code>
   *
   * @return The to.
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.model.Address getTo() {
    return to_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : to_;
  }

  /** <code>.Address to = 4;</code> */
  @java.lang.Override
  public com.mttbrt.ethtxmon.model.AddressOrBuilder getToOrBuilder() {
    return to_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : to_;
  }

  /**
   * <code>bytes value = 5;</code>
   *
   * @return The value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getValue() {
    return value_;
  }

  /**
   * <code>uint64 gas = 6;</code>
   *
   * @return The gas.
   */
  @java.lang.Override
  public long getGas() {
    return gas_;
  }

  /**
   * <code>uint64 gasPrice = 7;</code>
   *
   * @return The gasPrice.
   */
  @java.lang.Override
  public long getGasPrice() {
    return gasPrice_;
  }

  /**
   * <code>bool success = 8;</code>
   *
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  @java.lang.Override
  public boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!hash_.isEmpty()) {
      output.writeBytes(1, hash_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(2, timestamp_);
    }
    if (from_ != null) {
      output.writeMessage(3, getFrom());
    }
    if (to_ != null) {
      output.writeMessage(4, getTo());
    }
    if (!value_.isEmpty()) {
      output.writeBytes(5, value_);
    }
    if (gas_ != 0L) {
      output.writeUInt64(6, gas_);
    }
    if (gasPrice_ != 0L) {
      output.writeUInt64(7, gasPrice_);
    }
    if (success_) {
      output.writeBool(8, success_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!hash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, hash_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, timestamp_);
    }
    if (from_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getFrom());
    }
    if (to_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, getTo());
    }
    if (!value_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream.computeBytesSize(5, value_);
    }
    if (gas_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(6, gas_);
    }
    if (gasPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(7, gasPrice_);
    }
    if (success_) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(8, success_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof Tx other)) {
      return super.equals(obj);
    }

    if (!getHash().equals(other.getHash())) return false;
    if (getTimestamp() != other.getTimestamp()) return false;
    if (hasFrom() != other.hasFrom()) return false;
    if (hasFrom()) {
      if (!getFrom().equals(other.getFrom())) return false;
    }
    if (hasTo() != other.hasTo()) return false;
    if (hasTo()) {
      if (!getTo().equals(other.getTo())) return false;
    }
    if (!getValue().equals(other.getValue())) return false;
    if (getGas() != other.getGas()) return false;
    if (getGasPrice() != other.getGasPrice()) return false;
    if (getSuccess() != other.getSuccess()) return false;
    return getUnknownFields().equals(other.getUnknownFields());
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + getHash().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTimestamp());
    if (hasFrom()) {
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
    }
    if (hasTo()) {
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
    }
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + GAS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getGas());
    hash = (37 * hash) + GASPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getGasPrice());
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getSuccess());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tx> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mttbrt.ethtxmon.model.Tx getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /** Protobuf type {@code Tx} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:Tx)
      com.mttbrt.ethtxmon.model.TxOrBuilder {
    private int bitField0_;
    private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
    private long timestamp_;
    private com.mttbrt.ethtxmon.model.Address from_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.model.Address,
            com.mttbrt.ethtxmon.model.Address.Builder,
            com.mttbrt.ethtxmon.model.AddressOrBuilder>
        fromBuilder_;
    private com.mttbrt.ethtxmon.model.Address to_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.model.Address,
            com.mttbrt.ethtxmon.model.Address.Builder,
            com.mttbrt.ethtxmon.model.AddressOrBuilder>
        toBuilder_;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    private long gas_;
    private long gasPrice_;
    private boolean success_;

    // Construct using com.mttbrt.ethtxmon.model.Tx.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    public static com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.mttbrt.ethtxmon.model.Ethtx.internal_static_Tx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mttbrt.ethtxmon.model.Ethtx.internal_static_Tx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mttbrt.ethtxmon.model.Tx.class, com.mttbrt.ethtxmon.model.Tx.Builder.class);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hash_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      to_ = null;
      if (toBuilder_ != null) {
        toBuilder_.dispose();
        toBuilder_ = null;
      }
      value_ = com.google.protobuf.ByteString.EMPTY;
      gas_ = 0L;
      gasPrice_ = 0L;
      success_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.mttbrt.ethtxmon.model.Ethtx.internal_static_Tx_descriptor;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.model.Tx getDefaultInstanceForType() {
      return com.mttbrt.ethtxmon.model.Tx.getDefaultInstance();
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.model.Tx build() {
      com.mttbrt.ethtxmon.model.Tx result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.model.Tx buildPartial() {
      com.mttbrt.ethtxmon.model.Tx result = new com.mttbrt.ethtxmon.model.Tx(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mttbrt.ethtxmon.model.Tx result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hash_ = hash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.from_ = fromBuilder_ == null ? from_ : fromBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.to_ = toBuilder_ == null ? to_ : toBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.gas_ = gas_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.gasPrice_ = gasPrice_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mttbrt.ethtxmon.model.Tx) {
        return mergeFrom((com.mttbrt.ethtxmon.model.Tx) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mttbrt.ethtxmon.model.Tx other) {
      if (other == com.mttbrt.ethtxmon.model.Tx.getDefaultInstance()) return this;
      if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
        setHash(other.getHash());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasFrom()) {
        mergeFrom(other.getFrom());
      }
      if (other.hasTo()) {
        mergeTo(other.getTo());
      }
      if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
        setValue(other.getValue());
      }
      if (other.getGas() != 0L) {
        setGas(other.getGas());
      }
      if (other.getGasPrice() != 0L) {
        setGasPrice(other.getGasPrice());
      }
      if (other.getSuccess()) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                hash_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 16:
              {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
            case 26:
              {
                input.readMessage(getFromFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            case 34:
              {
                input.readMessage(getToFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
            case 42:
              {
                value_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
            case 48:
              {
                gas_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
            case 56:
              {
                gasPrice_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
            case 64:
              {
                success_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    /**
     * <code>bytes hash = 1;</code>
     *
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    /**
     * <code>bytes hash = 1;</code>
     *
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      hash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>bytes hash = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearHash() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hash_ = getDefaultInstance().getHash();
      onChanged();
      return this;
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     *
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     *
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 timestamp = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>.Address from = 3;</code>
     *
     * @return Whether the from field is set.
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>.Address from = 3;</code>
     *
     * @return The from.
     */
    public com.mttbrt.ethtxmon.model.Address getFrom() {
      if (fromBuilder_ == null) {
        return from_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : from_;
      } else {
        return fromBuilder_.getMessage();
      }
    }

    /** <code>.Address from = 3;</code> */
    public Builder setFrom(com.mttbrt.ethtxmon.model.Address value) {
      if (fromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        from_ = value;
      } else {
        fromBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /** <code>.Address from = 3;</code> */
    public Builder setFrom(com.mttbrt.ethtxmon.model.Address.Builder builderForValue) {
      if (fromBuilder_ == null) {
        from_ = builderForValue.build();
      } else {
        fromBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /** <code>.Address from = 3;</code> */
    public Builder mergeFrom(com.mttbrt.ethtxmon.model.Address value) {
      if (fromBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)
            && from_ != null
            && from_ != com.mttbrt.ethtxmon.model.Address.getDefaultInstance()) {
          getFromBuilder().mergeFrom(value);
        } else {
          from_ = value;
        }
      } else {
        fromBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /** <code>.Address from = 3;</code> */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000004);
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      onChanged();
      return this;
    }

    /** <code>.Address from = 3;</code> */
    public com.mttbrt.ethtxmon.model.Address.Builder getFromBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getFromFieldBuilder().getBuilder();
    }

    /** <code>.Address from = 3;</code> */
    public com.mttbrt.ethtxmon.model.AddressOrBuilder getFromOrBuilder() {
      if (fromBuilder_ != null) {
        return fromBuilder_.getMessageOrBuilder();
      } else {
        return from_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : from_;
      }
    }

    /** <code>.Address from = 3;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.model.Address,
            com.mttbrt.ethtxmon.model.Address.Builder,
            com.mttbrt.ethtxmon.model.AddressOrBuilder>
        getFromFieldBuilder() {
      if (fromBuilder_ == null) {
        fromBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.mttbrt.ethtxmon.model.Address,
                com.mttbrt.ethtxmon.model.Address.Builder,
                com.mttbrt.ethtxmon.model.AddressOrBuilder>(
                getFrom(), getParentForChildren(), isClean());
        from_ = null;
      }
      return fromBuilder_;
    }

    /**
     * <code>.Address to = 4;</code>
     *
     * @return Whether the to field is set.
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>.Address to = 4;</code>
     *
     * @return The to.
     */
    public com.mttbrt.ethtxmon.model.Address getTo() {
      if (toBuilder_ == null) {
        return to_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : to_;
      } else {
        return toBuilder_.getMessage();
      }
    }

    /** <code>.Address to = 4;</code> */
    public Builder setTo(com.mttbrt.ethtxmon.model.Address value) {
      if (toBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
      } else {
        toBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /** <code>.Address to = 4;</code> */
    public Builder setTo(com.mttbrt.ethtxmon.model.Address.Builder builderForValue) {
      if (toBuilder_ == null) {
        to_ = builderForValue.build();
      } else {
        toBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /** <code>.Address to = 4;</code> */
    public Builder mergeTo(com.mttbrt.ethtxmon.model.Address value) {
      if (toBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)
            && to_ != null
            && to_ != com.mttbrt.ethtxmon.model.Address.getDefaultInstance()) {
          getToBuilder().mergeFrom(value);
        } else {
          to_ = value;
        }
      } else {
        toBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /** <code>.Address to = 4;</code> */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000008);
      to_ = null;
      if (toBuilder_ != null) {
        toBuilder_.dispose();
        toBuilder_ = null;
      }
      onChanged();
      return this;
    }

    /** <code>.Address to = 4;</code> */
    public com.mttbrt.ethtxmon.model.Address.Builder getToBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getToFieldBuilder().getBuilder();
    }

    /** <code>.Address to = 4;</code> */
    public com.mttbrt.ethtxmon.model.AddressOrBuilder getToOrBuilder() {
      if (toBuilder_ != null) {
        return toBuilder_.getMessageOrBuilder();
      } else {
        return to_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : to_;
      }
    }

    /** <code>.Address to = 4;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.model.Address,
            com.mttbrt.ethtxmon.model.Address.Builder,
            com.mttbrt.ethtxmon.model.AddressOrBuilder>
        getToFieldBuilder() {
      if (toBuilder_ == null) {
        toBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.mttbrt.ethtxmon.model.Address,
                com.mttbrt.ethtxmon.model.Address.Builder,
                com.mttbrt.ethtxmon.model.AddressOrBuilder>(
                getTo(), getParentForChildren(), isClean());
        to_ = null;
      }
      return toBuilder_;
    }

    /**
     * <code>bytes value = 5;</code>
     *
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    /**
     * <code>bytes value = 5;</code>
     *
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      value_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    /**
     * <code>bytes value = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }

    /**
     * <code>uint64 gas = 6;</code>
     *
     * @return The gas.
     */
    @java.lang.Override
    public long getGas() {
      return gas_;
    }

    /**
     * <code>uint64 gas = 6;</code>
     *
     * @param value The gas to set.
     * @return This builder for chaining.
     */
    public Builder setGas(long value) {

      gas_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 gas = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearGas() {
      bitField0_ = (bitField0_ & ~0x00000020);
      gas_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 gasPrice = 7;</code>
     *
     * @return The gasPrice.
     */
    @java.lang.Override
    public long getGasPrice() {
      return gasPrice_;
    }

    /**
     * <code>uint64 gasPrice = 7;</code>
     *
     * @param value The gasPrice to set.
     * @return This builder for chaining.
     */
    public Builder setGasPrice(long value) {

      gasPrice_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 gasPrice = 7;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearGasPrice() {
      bitField0_ = (bitField0_ & ~0x00000040);
      gasPrice_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>bool success = 8;</code>
     *
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 8;</code>
     *
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000080);
      success_ = false;
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:Tx)
  }
}
