// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.model;

public interface TxRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:TxRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Address address = 1;</code>
   *
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 1;</code>
   *
   * @return The address.
   */
  com.mttbrt.ethtxmon.model.Address getAddress();
  /** <code>.Address address = 1;</code> */
  com.mttbrt.ethtxmon.model.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>bytes txHash = 2;</code>
   *
   * @return The txHash.
   */
  com.google.protobuf.ByteString getTxHash();
}
