// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.model;

/** Protobuf type {@code TxRequest} */
public final class TxRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:TxRequest)
    TxRequestOrBuilder {
  public static final int ADDRESS_FIELD_NUMBER = 1;
  public static final int TXHASH_FIELD_NUMBER = 2;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:TxRequest)
  private static final com.mttbrt.ethtxmon.model.TxRequest DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<TxRequest> PARSER =
      new com.google.protobuf.AbstractParser<TxRequest>() {
        @java.lang.Override
        public TxRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  static {
    DEFAULT_INSTANCE = new com.mttbrt.ethtxmon.model.TxRequest();
  }

  private com.mttbrt.ethtxmon.model.Address address_;
  private com.google.protobuf.ByteString txHash_ = com.google.protobuf.ByteString.EMPTY;
  private byte memoizedIsInitialized = -1;
  // Use TxRequest.newBuilder() to construct.
  private TxRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TxRequest() {
    txHash_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.mttbrt.ethtxmon.model.Ethtx.internal_static_TxRequest_descriptor;
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.mttbrt.ethtxmon.model.TxRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.mttbrt.ethtxmon.model.TxRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<TxRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new TxRequest();
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mttbrt.ethtxmon.model.Ethtx.internal_static_TxRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mttbrt.ethtxmon.model.TxRequest.class,
            com.mttbrt.ethtxmon.model.TxRequest.Builder.class);
  }

  /**
   * <code>.Address address = 1;</code>
   *
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }

  /**
   * <code>.Address address = 1;</code>
   *
   * @return The address.
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.model.Address getAddress() {
    return address_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : address_;
  }

  /** <code>.Address address = 1;</code> */
  @java.lang.Override
  public com.mttbrt.ethtxmon.model.AddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : address_;
  }

  /**
   * <code>bytes txHash = 2;</code>
   *
   * @return The txHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTxHash() {
    return txHash_;
  }

  @java.lang.Override
  public boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (address_ != null) {
      output.writeMessage(1, getAddress());
    }
    if (!txHash_.isEmpty()) {
      output.writeBytes(2, txHash_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getAddress());
    }
    if (!txHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, txHash_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof TxRequest other)) {
      return super.equals(obj);
    }

    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress().equals(other.getAddress())) return false;
    }
    if (!getTxHash().equals(other.getTxHash())) return false;
    return getUnknownFields().equals(other.getUnknownFields());
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + TXHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTxHash().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TxRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mttbrt.ethtxmon.model.TxRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /** Protobuf type {@code TxRequest} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:TxRequest)
      com.mttbrt.ethtxmon.model.TxRequestOrBuilder {
    private int bitField0_;
    private com.mttbrt.ethtxmon.model.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.model.Address,
            com.mttbrt.ethtxmon.model.Address.Builder,
            com.mttbrt.ethtxmon.model.AddressOrBuilder>
        addressBuilder_;
    private com.google.protobuf.ByteString txHash_ = com.google.protobuf.ByteString.EMPTY;

    // Construct using com.mttbrt.ethtxmon.model.TxRequest.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    public static com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.mttbrt.ethtxmon.model.Ethtx.internal_static_TxRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mttbrt.ethtxmon.model.Ethtx.internal_static_TxRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mttbrt.ethtxmon.model.TxRequest.class,
              com.mttbrt.ethtxmon.model.TxRequest.Builder.class);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      txHash_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.mttbrt.ethtxmon.model.Ethtx.internal_static_TxRequest_descriptor;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.model.TxRequest getDefaultInstanceForType() {
      return com.mttbrt.ethtxmon.model.TxRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.model.TxRequest build() {
      com.mttbrt.ethtxmon.model.TxRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.model.TxRequest buildPartial() {
      com.mttbrt.ethtxmon.model.TxRequest result = new com.mttbrt.ethtxmon.model.TxRequest(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mttbrt.ethtxmon.model.TxRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.address_ = addressBuilder_ == null ? address_ : addressBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.txHash_ = txHash_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mttbrt.ethtxmon.model.TxRequest) {
        return mergeFrom((com.mttbrt.ethtxmon.model.TxRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mttbrt.ethtxmon.model.TxRequest other) {
      if (other == com.mttbrt.ethtxmon.model.TxRequest.getDefaultInstance()) return this;
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.getTxHash() != com.google.protobuf.ByteString.EMPTY) {
        setTxHash(other.getTxHash());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getAddressFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                txHash_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    /**
     * <code>.Address address = 1;</code>
     *
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.Address address = 1;</code>
     *
     * @return The address.
     */
    public com.mttbrt.ethtxmon.model.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }

    /** <code>.Address address = 1;</code> */
    public Builder setAddress(com.mttbrt.ethtxmon.model.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /** <code>.Address address = 1;</code> */
    public Builder setAddress(com.mttbrt.ethtxmon.model.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /** <code>.Address address = 1;</code> */
    public Builder mergeAddress(com.mttbrt.ethtxmon.model.Address value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)
            && address_ != null
            && address_ != com.mttbrt.ethtxmon.model.Address.getDefaultInstance()) {
          getAddressBuilder().mergeFrom(value);
        } else {
          address_ = value;
        }
      } else {
        addressBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /** <code>.Address address = 1;</code> */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000001);
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      onChanged();
      return this;
    }

    /** <code>.Address address = 1;</code> */
    public com.mttbrt.ethtxmon.model.Address.Builder getAddressBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }

    /** <code>.Address address = 1;</code> */
    public com.mttbrt.ethtxmon.model.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ? com.mttbrt.ethtxmon.model.Address.getDefaultInstance() : address_;
      }
    }

    /** <code>.Address address = 1;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.model.Address,
            com.mttbrt.ethtxmon.model.Address.Builder,
            com.mttbrt.ethtxmon.model.AddressOrBuilder>
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.mttbrt.ethtxmon.model.Address,
                com.mttbrt.ethtxmon.model.Address.Builder,
                com.mttbrt.ethtxmon.model.AddressOrBuilder>(
                getAddress(), getParentForChildren(), isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    /**
     * <code>bytes txHash = 2;</code>
     *
     * @return The txHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTxHash() {
      return txHash_;
    }
    /**
     * <code>bytes txHash = 2;</code>
     *
     * @param value The txHash to set.
     * @return This builder for chaining.
     */
    public Builder setTxHash(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      txHash_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes txHash = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearTxHash() {
      bitField0_ = (bitField0_ & ~0x00000002);
      txHash_ = getDefaultInstance().getTxHash();
      onChanged();
      return this;
    }

    @java.lang.Override
    public Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:TxRequest)
  }
}
