// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.grpc.model;

public interface RequestTxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestTx)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 1;</code>
   * @return The address.
   */
  com.mttbrt.ethtxmon.grpc.model.Address getAddress();
  /**
   * <code>.Address address = 1;</code>
   */
  com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>uint32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();
}
