// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.grpc.model;

/**
 * Protobuf type {@code RequestTx}
 */
public final class RequestTx extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RequestTx)
    RequestTxOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestTx.newBuilder() to construct.
  private RequestTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestTx() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestTx();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_RequestTx_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_RequestTx_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mttbrt.ethtxmon.grpc.model.RequestTx.class, com.mttbrt.ethtxmon.grpc.model.RequestTx.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private com.mttbrt.ethtxmon.grpc.model.Address address_;
  /**
   * <code>.Address address = 1;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.Address address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.Address getAddress() {
    return address_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.Address address = 1;</code>
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : address_;
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private int limit_ = 0;
  /**
   * <code>uint32 limit = 2;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (address_ != null) {
      output.writeMessage(1, getAddress());
    }
    if (limit_ != 0) {
      output.writeUInt32(2, limit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAddress());
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, limit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mttbrt.ethtxmon.grpc.model.RequestTx)) {
      return super.equals(obj);
    }
    com.mttbrt.ethtxmon.grpc.model.RequestTx other = (com.mttbrt.ethtxmon.grpc.model.RequestTx) obj;

    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (getLimit()
        != other.getLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mttbrt.ethtxmon.grpc.model.RequestTx parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mttbrt.ethtxmon.grpc.model.RequestTx prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RequestTx}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RequestTx)
      com.mttbrt.ethtxmon.grpc.model.RequestTxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_RequestTx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_RequestTx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mttbrt.ethtxmon.grpc.model.RequestTx.class, com.mttbrt.ethtxmon.grpc.model.RequestTx.Builder.class);
    }

    // Construct using com.mttbrt.ethtxmon.grpc.model.RequestTx.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      limit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_RequestTx_descriptor;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.grpc.model.RequestTx getDefaultInstanceForType() {
      return com.mttbrt.ethtxmon.grpc.model.RequestTx.getDefaultInstance();
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.grpc.model.RequestTx build() {
      com.mttbrt.ethtxmon.grpc.model.RequestTx result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.grpc.model.RequestTx buildPartial() {
      com.mttbrt.ethtxmon.grpc.model.RequestTx result = new com.mttbrt.ethtxmon.grpc.model.RequestTx(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mttbrt.ethtxmon.grpc.model.RequestTx result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.address_ = addressBuilder_ == null
            ? address_
            : addressBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.limit_ = limit_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mttbrt.ethtxmon.grpc.model.RequestTx) {
        return mergeFrom((com.mttbrt.ethtxmon.grpc.model.RequestTx)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mttbrt.ethtxmon.grpc.model.RequestTx other) {
      if (other == com.mttbrt.ethtxmon.grpc.model.RequestTx.getDefaultInstance()) return this;
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              limit_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.mttbrt.ethtxmon.grpc.model.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.Address address = 1;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Address address = 1;</code>
     * @return The address.
     */
    public com.mttbrt.ethtxmon.grpc.model.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.Address address = 1;</code>
     */
    public Builder setAddress(com.mttbrt.ethtxmon.grpc.model.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Address address = 1;</code>
     */
    public Builder setAddress(
        com.mttbrt.ethtxmon.grpc.model.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Address address = 1;</code>
     */
    public Builder mergeAddress(com.mttbrt.ethtxmon.grpc.model.Address value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          address_ != null &&
          address_ != com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance()) {
          getAddressBuilder().mergeFrom(value);
        } else {
          address_ = value;
        }
      } else {
        addressBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Address address = 1;</code>
     */
    public Builder clearAddress() {
      bitField0_ = (bitField0_ & ~0x00000001);
      address_ = null;
      if (addressBuilder_ != null) {
        addressBuilder_.dispose();
        addressBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Address address = 1;</code>
     */
    public com.mttbrt.ethtxmon.grpc.model.Address.Builder getAddressBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.Address address = 1;</code>
     */
    public com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.Address address = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private int limit_ ;
    /**
     * <code>uint32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <code>uint32 limit = 2;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {

      limit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 limit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000002);
      limit_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RequestTx)
  }

  // @@protoc_insertion_point(class_scope:RequestTx)
  private static final com.mttbrt.ethtxmon.grpc.model.RequestTx DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mttbrt.ethtxmon.grpc.model.RequestTx();
  }

  public static com.mttbrt.ethtxmon.grpc.model.RequestTx getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestTx>
      PARSER = new com.google.protobuf.AbstractParser<RequestTx>() {
    @java.lang.Override
    public RequestTx parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestTx> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestTx> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.RequestTx getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

