// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.grpc.model;

/**
 * Protobuf type {@code Tx}
 */
public final class Tx extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Tx)
    TxOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Tx.newBuilder() to construct.
  private Tx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Tx() {
    hash_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Tx();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_Tx_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_Tx_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mttbrt.ethtxmon.grpc.model.Tx.class, com.mttbrt.ethtxmon.grpc.model.Tx.Builder.class);
  }

  public static final int HASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes hash = 1;</code>
   * @return The hash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHash() {
    return hash_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_ = 0L;
  /**
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int FROM_FIELD_NUMBER = 3;
  private com.mttbrt.ethtxmon.grpc.model.Address from_;
  /**
   * <code>.Address from = 3;</code>
   * @return Whether the from field is set.
   */
  @java.lang.Override
  public boolean hasFrom() {
    return from_ != null;
  }
  /**
   * <code>.Address from = 3;</code>
   * @return The from.
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.Address getFrom() {
    return from_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : from_;
  }
  /**
   * <code>.Address from = 3;</code>
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getFromOrBuilder() {
    return from_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : from_;
  }

  public static final int TO_FIELD_NUMBER = 4;
  private com.mttbrt.ethtxmon.grpc.model.Address to_;
  /**
   * <code>.Address to = 4;</code>
   * @return Whether the to field is set.
   */
  @java.lang.Override
  public boolean hasTo() {
    return to_ != null;
  }
  /**
   * <code>.Address to = 4;</code>
   * @return The to.
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.Address getTo() {
    return to_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : to_;
  }
  /**
   * <code>.Address to = 4;</code>
   */
  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getToOrBuilder() {
    return to_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : to_;
  }

  public static final int VALUE_FIELD_NUMBER = 5;
  private long value_ = 0L;
  /**
   * <code>uint64 value = 5;</code>
   * @return The value.
   */
  @java.lang.Override
  public long getValue() {
    return value_;
  }

  public static final int GAS_FIELD_NUMBER = 6;
  private long gas_ = 0L;
  /**
   * <code>uint64 gas = 6;</code>
   * @return The gas.
   */
  @java.lang.Override
  public long getGas() {
    return gas_;
  }

  public static final int GASPRICE_FIELD_NUMBER = 7;
  private long gasPrice_ = 0L;
  /**
   * <code>uint64 gasPrice = 7;</code>
   * @return The gasPrice.
   */
  @java.lang.Override
  public long getGasPrice() {
    return gasPrice_;
  }

  public static final int ISERROR_FIELD_NUMBER = 8;
  private boolean isError_ = false;
  /**
   * <code>bool isError = 8;</code>
   * @return The isError.
   */
  @java.lang.Override
  public boolean getIsError() {
    return isError_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!hash_.isEmpty()) {
      output.writeBytes(1, hash_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(2, timestamp_);
    }
    if (from_ != null) {
      output.writeMessage(3, getFrom());
    }
    if (to_ != null) {
      output.writeMessage(4, getTo());
    }
    if (value_ != 0L) {
      output.writeUInt64(5, value_);
    }
    if (gas_ != 0L) {
      output.writeUInt64(6, gas_);
    }
    if (gasPrice_ != 0L) {
      output.writeUInt64(7, gasPrice_);
    }
    if (isError_ != false) {
      output.writeBool(8, isError_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!hash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, hash_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, timestamp_);
    }
    if (from_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFrom());
    }
    if (to_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTo());
    }
    if (value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, value_);
    }
    if (gas_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, gas_);
    }
    if (gasPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, gasPrice_);
    }
    if (isError_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isError_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mttbrt.ethtxmon.grpc.model.Tx)) {
      return super.equals(obj);
    }
    com.mttbrt.ethtxmon.grpc.model.Tx other = (com.mttbrt.ethtxmon.grpc.model.Tx) obj;

    if (!getHash()
        .equals(other.getHash())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (hasFrom() != other.hasFrom()) return false;
    if (hasFrom()) {
      if (!getFrom()
          .equals(other.getFrom())) return false;
    }
    if (hasTo() != other.hasTo()) return false;
    if (hasTo()) {
      if (!getTo()
          .equals(other.getTo())) return false;
    }
    if (getValue()
        != other.getValue()) return false;
    if (getGas()
        != other.getGas()) return false;
    if (getGasPrice()
        != other.getGasPrice()) return false;
    if (getIsError()
        != other.getIsError()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + getHash().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (hasFrom()) {
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
    }
    if (hasTo()) {
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
    }
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValue());
    hash = (37 * hash) + GAS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGas());
    hash = (37 * hash) + GASPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGasPrice());
    hash = (37 * hash) + ISERROR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsError());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mttbrt.ethtxmon.grpc.model.Tx parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mttbrt.ethtxmon.grpc.model.Tx parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mttbrt.ethtxmon.grpc.model.Tx parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mttbrt.ethtxmon.grpc.model.Tx prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Tx}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Tx)
      com.mttbrt.ethtxmon.grpc.model.TxOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_Tx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_Tx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mttbrt.ethtxmon.grpc.model.Tx.class, com.mttbrt.ethtxmon.grpc.model.Tx.Builder.class);
    }

    // Construct using com.mttbrt.ethtxmon.grpc.model.Tx.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hash_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      to_ = null;
      if (toBuilder_ != null) {
        toBuilder_.dispose();
        toBuilder_ = null;
      }
      value_ = 0L;
      gas_ = 0L;
      gasPrice_ = 0L;
      isError_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mttbrt.ethtxmon.grpc.model.Ethtx.internal_static_Tx_descriptor;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.grpc.model.Tx getDefaultInstanceForType() {
      return com.mttbrt.ethtxmon.grpc.model.Tx.getDefaultInstance();
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.grpc.model.Tx build() {
      com.mttbrt.ethtxmon.grpc.model.Tx result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mttbrt.ethtxmon.grpc.model.Tx buildPartial() {
      com.mttbrt.ethtxmon.grpc.model.Tx result = new com.mttbrt.ethtxmon.grpc.model.Tx(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mttbrt.ethtxmon.grpc.model.Tx result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hash_ = hash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.from_ = fromBuilder_ == null
            ? from_
            : fromBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.to_ = toBuilder_ == null
            ? to_
            : toBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.gas_ = gas_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.gasPrice_ = gasPrice_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.isError_ = isError_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mttbrt.ethtxmon.grpc.model.Tx) {
        return mergeFrom((com.mttbrt.ethtxmon.grpc.model.Tx)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mttbrt.ethtxmon.grpc.model.Tx other) {
      if (other == com.mttbrt.ethtxmon.grpc.model.Tx.getDefaultInstance()) return this;
      if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
        setHash(other.getHash());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasFrom()) {
        mergeFrom(other.getFrom());
      }
      if (other.hasTo()) {
        mergeTo(other.getTo());
      }
      if (other.getValue() != 0L) {
        setValue(other.getValue());
      }
      if (other.getGas() != 0L) {
        setGas(other.getGas());
      }
      if (other.getGasPrice() != 0L) {
        setGasPrice(other.getGasPrice());
      }
      if (other.getIsError() != false) {
        setIsError(other.getIsError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hash_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              timestamp_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getFromFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getToFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              value_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              gas_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              gasPrice_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              isError_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes hash = 1;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    /**
     * <code>bytes hash = 1;</code>
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      hash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes hash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHash() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hash_ = getDefaultInstance().getHash();
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 2;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.mttbrt.ethtxmon.grpc.model.Address from_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder> fromBuilder_;
    /**
     * <code>.Address from = 3;</code>
     * @return Whether the from field is set.
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.Address from = 3;</code>
     * @return The from.
     */
    public com.mttbrt.ethtxmon.grpc.model.Address getFrom() {
      if (fromBuilder_ == null) {
        return from_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : from_;
      } else {
        return fromBuilder_.getMessage();
      }
    }
    /**
     * <code>.Address from = 3;</code>
     */
    public Builder setFrom(com.mttbrt.ethtxmon.grpc.model.Address value) {
      if (fromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        from_ = value;
      } else {
        fromBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Address from = 3;</code>
     */
    public Builder setFrom(
        com.mttbrt.ethtxmon.grpc.model.Address.Builder builderForValue) {
      if (fromBuilder_ == null) {
        from_ = builderForValue.build();
      } else {
        fromBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Address from = 3;</code>
     */
    public Builder mergeFrom(com.mttbrt.ethtxmon.grpc.model.Address value) {
      if (fromBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          from_ != null &&
          from_ != com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance()) {
          getFromBuilder().mergeFrom(value);
        } else {
          from_ = value;
        }
      } else {
        fromBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Address from = 3;</code>
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000004);
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Address from = 3;</code>
     */
    public com.mttbrt.ethtxmon.grpc.model.Address.Builder getFromBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getFromFieldBuilder().getBuilder();
    }
    /**
     * <code>.Address from = 3;</code>
     */
    public com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getFromOrBuilder() {
      if (fromBuilder_ != null) {
        return fromBuilder_.getMessageOrBuilder();
      } else {
        return from_ == null ?
            com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : from_;
      }
    }
    /**
     * <code>.Address from = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder> 
        getFromFieldBuilder() {
      if (fromBuilder_ == null) {
        fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder>(
                getFrom(),
                getParentForChildren(),
                isClean());
        from_ = null;
      }
      return fromBuilder_;
    }

    private com.mttbrt.ethtxmon.grpc.model.Address to_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder> toBuilder_;
    /**
     * <code>.Address to = 4;</code>
     * @return Whether the to field is set.
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.Address to = 4;</code>
     * @return The to.
     */
    public com.mttbrt.ethtxmon.grpc.model.Address getTo() {
      if (toBuilder_ == null) {
        return to_ == null ? com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : to_;
      } else {
        return toBuilder_.getMessage();
      }
    }
    /**
     * <code>.Address to = 4;</code>
     */
    public Builder setTo(com.mttbrt.ethtxmon.grpc.model.Address value) {
      if (toBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
      } else {
        toBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Address to = 4;</code>
     */
    public Builder setTo(
        com.mttbrt.ethtxmon.grpc.model.Address.Builder builderForValue) {
      if (toBuilder_ == null) {
        to_ = builderForValue.build();
      } else {
        toBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Address to = 4;</code>
     */
    public Builder mergeTo(com.mttbrt.ethtxmon.grpc.model.Address value) {
      if (toBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          to_ != null &&
          to_ != com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance()) {
          getToBuilder().mergeFrom(value);
        } else {
          to_ = value;
        }
      } else {
        toBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.Address to = 4;</code>
     */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000008);
      to_ = null;
      if (toBuilder_ != null) {
        toBuilder_.dispose();
        toBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Address to = 4;</code>
     */
    public com.mttbrt.ethtxmon.grpc.model.Address.Builder getToBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getToFieldBuilder().getBuilder();
    }
    /**
     * <code>.Address to = 4;</code>
     */
    public com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getToOrBuilder() {
      if (toBuilder_ != null) {
        return toBuilder_.getMessageOrBuilder();
      } else {
        return to_ == null ?
            com.mttbrt.ethtxmon.grpc.model.Address.getDefaultInstance() : to_;
      }
    }
    /**
     * <code>.Address to = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder> 
        getToFieldBuilder() {
      if (toBuilder_ == null) {
        toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mttbrt.ethtxmon.grpc.model.Address, com.mttbrt.ethtxmon.grpc.model.Address.Builder, com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder>(
                getTo(),
                getParentForChildren(),
                isClean());
        to_ = null;
      }
      return toBuilder_;
    }

    private long value_ ;
    /**
     * <code>uint64 value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }
    /**
     * <code>uint64 value = 5;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(long value) {

      value_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      value_ = 0L;
      onChanged();
      return this;
    }

    private long gas_ ;
    /**
     * <code>uint64 gas = 6;</code>
     * @return The gas.
     */
    @java.lang.Override
    public long getGas() {
      return gas_;
    }
    /**
     * <code>uint64 gas = 6;</code>
     * @param value The gas to set.
     * @return This builder for chaining.
     */
    public Builder setGas(long value) {

      gas_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gas = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGas() {
      bitField0_ = (bitField0_ & ~0x00000020);
      gas_ = 0L;
      onChanged();
      return this;
    }

    private long gasPrice_ ;
    /**
     * <code>uint64 gasPrice = 7;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public long getGasPrice() {
      return gasPrice_;
    }
    /**
     * <code>uint64 gasPrice = 7;</code>
     * @param value The gasPrice to set.
     * @return This builder for chaining.
     */
    public Builder setGasPrice(long value) {

      gasPrice_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gasPrice = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasPrice() {
      bitField0_ = (bitField0_ & ~0x00000040);
      gasPrice_ = 0L;
      onChanged();
      return this;
    }

    private boolean isError_ ;
    /**
     * <code>bool isError = 8;</code>
     * @return The isError.
     */
    @java.lang.Override
    public boolean getIsError() {
      return isError_;
    }
    /**
     * <code>bool isError = 8;</code>
     * @param value The isError to set.
     * @return This builder for chaining.
     */
    public Builder setIsError(boolean value) {

      isError_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool isError = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsError() {
      bitField0_ = (bitField0_ & ~0x00000080);
      isError_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Tx)
  }

  // @@protoc_insertion_point(class_scope:Tx)
  private static final com.mttbrt.ethtxmon.grpc.model.Tx DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mttbrt.ethtxmon.grpc.model.Tx();
  }

  public static com.mttbrt.ethtxmon.grpc.model.Tx getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Tx>
      PARSER = new com.google.protobuf.AbstractParser<Tx>() {
    @java.lang.Override
    public Tx parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Tx> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Tx> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mttbrt.ethtxmon.grpc.model.Tx getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

