// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ethtx.proto

package com.mttbrt.ethtxmon.grpc.model;

public interface TxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Tx)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes hash = 1;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.Address from = 3;</code>
   * @return Whether the from field is set.
   */
  boolean hasFrom();
  /**
   * <code>.Address from = 3;</code>
   * @return The from.
   */
  com.mttbrt.ethtxmon.grpc.model.Address getFrom();
  /**
   * <code>.Address from = 3;</code>
   */
  com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getFromOrBuilder();

  /**
   * <code>.Address to = 4;</code>
   * @return Whether the to field is set.
   */
  boolean hasTo();
  /**
   * <code>.Address to = 4;</code>
   * @return The to.
   */
  com.mttbrt.ethtxmon.grpc.model.Address getTo();
  /**
   * <code>.Address to = 4;</code>
   */
  com.mttbrt.ethtxmon.grpc.model.AddressOrBuilder getToOrBuilder();

  /**
   * <code>uint64 value = 5;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <code>uint64 gas = 6;</code>
   * @return The gas.
   */
  long getGas();

  /**
   * <code>uint64 gasPrice = 7;</code>
   * @return The gasPrice.
   */
  long getGasPrice();

  /**
   * <code>bool isError = 8;</code>
   * @return The isError.
   */
  boolean getIsError();
}
